### ISSUE TITLE
可以留个联系方式么,我们也要基于greendao3.2.2的插件二次开发

### ISSUE THREAD

**Issue by ktl-111** [wurensen/Greendao3GradlePlugin#1]

**Comment by wurensen** [comment]
@qaz5506811123 因为greendao插件源码没有开源，这个需要自己去反编译。我写这个插件，也是反编译看实现，然后尽可能用它原有的task实现。你们需要二次开发的功能比较复杂的话，建议联系greendao的相关人员，看能不能开源给你们。

**Comment by ktl-111** [comment]
好的,谢谢
