### ISSUE TITLE
这个插件的源码在哪里，现在Gradle 7.0 下增量编译有问题

### ISSUE THREAD

**Issue by jepack** [wurensen/Greendao3GradlePlugin#2]
现在Gradle 7.0 下增量编译，每次都会重新生成数据库类，如果有3.3.0 源码就可以尝试修复下

**Comment by wurensen** [comment]
@jepack 这个库已经不维护了，因为当时官方版本已经修复了问题。我当时是反编译看大致逻辑，并没有源码。
